"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VERIFICATIONCODELENGTH = exports.PASSWORD_EMAIL = exports.USER_EMAIL = exports.EMAIL_SERVICE = exports.EMAIL_REJECT = exports.EMAIL_PORT = exports.EMAIL_CIPHERS = exports.EMAIL_ADDRESS = exports.MY_SECRET_PRISMA_YML = exports.TOKEN_EXPIRY_TIME = exports.TOKEN_SECRET = exports.SERVER_PORT = void 0;
const env = require("env-var");
const SERVER_PORT = env.get('SERVER_PORT').asPortNumber();
exports.SERVER_PORT = SERVER_PORT;
const TOKEN_SECRET = env.get('TOKEN_SECRET').asString();
exports.TOKEN_SECRET = TOKEN_SECRET;
const TOKEN_EXPIRY_TIME = env.get('TOKEN_EXPIRY_TIME').asString();
exports.TOKEN_EXPIRY_TIME = TOKEN_EXPIRY_TIME;
const MY_SECRET_PRISMA_YML = env.get('MY_SECRET_PRISMA_YML').asString();
exports.MY_SECRET_PRISMA_YML = MY_SECRET_PRISMA_YML;
const EMAIL_SERVICE = env.get('EMAIL_SERVICE').asString();
exports.EMAIL_SERVICE = EMAIL_SERVICE;
const EMAIL_PORT = env.get('EMAIL_PORT').asPortNumber();
exports.EMAIL_PORT = EMAIL_PORT;
const EMAIL_CIPHERS = env.get('EMAIL_CIPHERS').asString();
exports.EMAIL_CIPHERS = EMAIL_CIPHERS;
const EMAIL_REJECT = env.get('EMAIL_REJECT').asBool();
exports.EMAIL_REJECT = EMAIL_REJECT;
const USER_EMAIL = env.get('USER_EMAIL').asString();
exports.USER_EMAIL = USER_EMAIL;
const PASSWORD_EMAIL = env.get('PASSWORD_EMAIL').asString();
exports.PASSWORD_EMAIL = PASSWORD_EMAIL;
const EMAIL_ADDRESS = env.get('EMAIL_ADDRESS').asString();
exports.EMAIL_ADDRESS = EMAIL_ADDRESS;
const VERIFICATIONCODELENGTH = env.get('VERIFICATIONCODELENGTH').asIntPositive();
exports.VERIFICATIONCODELENGTH = VERIFICATIONCODELENGTH;
//# sourceMappingURL=env.config.js.map